### ISSUE TITLE
data for result reproducibility

### ISSUE THREAD

**Issue by jerrygaoLondon** [USC-Melady/AMDN-HAGE-KDD21#1]
Thanks for sharing your train set and covid-10 data. Few more data is needed to validate and benchmark against your work:

1) can you please share a list of suspended Twitter accounts used in your experiment for examining and estimate the performance of proposed model via overlapped account ?

2) can you please share IRA dataset tweets ids used in the experiment including trolls and non-trolls activities (1.2M obtained from Luceri et al, 2020) ? I understood that there is potential constraints and 3rd policy for data sharing. That is OK if the dataset cannot be fully shared. any link or sharing account set used in the experiment  would be appreciated. 

thanks

**Comment by ksharmar** [comment]
Hi Jerry, 

1. For covid data, I have updated the repository (in the kdd_data directory) to include the suspended users in our experiment results. (which was from the time we ran our experiments. Twitter may have suspended more accounts later). 
Twitter API can be used to get the suspended accounts - user_status = api.get_user(uid). If exception occurs then the status of deleted or suspended can be logged by catching the exception: except tweepy.TweepError as e: logging.info('Exception: {}'.format(e)). 

For other rows in the overlapped accounts table: State-backed, coupled and targets (you will need to request data access from Twitter directly - https://transparency.twitter.com/en/reports/information-operations.html).

2. Could you pls send me an email about the IRA dataset request and cc Emilio Ferrara, since there might be restrictions.
